name: seqWell-nf
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - bbmap=38.90
  - bwa=0.7.17
  - samtools=1
  - bedtools=2.30
  - seqtk=1.3
  - unicycler=0.5
  - spades=3.15.4
  - blast=2.13.0
  - python=3.7.16
  - pip:
    - pandas==1.3.5
    - xlsxwriter==3.0.8
    - openpyxl==3.1.1
    - matplotlib==3.5.3
